language: python
sudo: false
addons:
  firefox: latest
python:
  - 2.7
  - 3.6
env:
  - DJANGO="Django==1.11.14" MOZ_HEADLESS=1
  - DJANGO="Django==2.0.7" MOZ_HEADLESS=1
  - DJANGO="https://www.djangoproject.com/download/2.1b1/tarball/" MOZ_HEADLESS=1
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
  - python: 2.7
    env: DJANGO="Django==2.0.7" MOZ_HEADLESS=1
  - python: 2.7
    env: DJANGO="https://www.djangoproject.com/download/2.1b1/tarball/" MOZ_HEADLESS=1
