language: python
sudo: false
addons:
  firefox: latest
matrix:
  include:
    - python: 2.7
      env: DJANGO="Django==1.11.25" MOZ_HEADLESS=1 DJANGO_MPTT="django-mptt==0.9.1"
    - python: 3.6
      env: DJANGO="Django==1.11.25" MOZ_HEADLESS=1 DJANGO_MPTT="django-mptt==0.10.0"
    - python: 3.7
      env: DJANGO="Django==2.0.13" MOZ_HEADLESS=1 DJANGO_MPTT="django-mptt==0.10.0"
      dist: xenial
      sudo: true
    - python: 3.7
      env: DJANGO="Django==2.1.13" MOZ_HEADLESS=1 DJANGO_MPTT="django-mptt==0.10.0"
      dist: xenial
      sudo: true
    - python: 3.7
      env: DJANGO="Django==2.2.6" MOZ_HEADLESS=1 DJANGO_MPTT="django-mptt==0.10.0"
      dist: xenial
      sudo: true
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install $DJANGO $DJANGO_MPTT
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
