language: python
dist: bionic
addons:
  firefox: latest
matrix:
  include:
    - python: 3.7
      env: DJANGO="Django==2.0.13" MOZ_HEADLESS=1
    - python: 3.7
      env: DJANGO="Django==2.1.15" MOZ_HEADLESS=1
    - python: 3.7
      env: DJANGO="Django==2.2.11" MOZ_HEADLESS=1
    - python: 3.7
      env: DJANGO="Django==3.0.4" MOZ_HEADLESS=1
    - python: 3.8
      env: DJANGO="Django==3.0.4" MOZ_HEADLESS=1
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python -Wd example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
