language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=Django==1.4.17
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.9
  - DJANGO=Django==1.7.2
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - python setup.py install
script:
  - cd example_project
  - python manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,django_mptt_example manage.py test django_mptt_example
  - coverage report
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
after_success:
  - coveralls
  - cd ..
  - covio
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.2
    - python: 3.3
      env: DJANGO=Django==1.4.17
    - python: 3.4
      env: DJANGO=Django==1.4.17
    - python: pypy
      env: DJANGO=Django==1.4.17
    - python: pypy
      env: DJANGO=Django==1.5.12
    - python: pypy
      env: DJANGO=Django==1.6.9
branches:
  only:
    - master
