language: python
dist: bionic
addons:
  apt:
    packages:
      - ffmpeg
services:
  - postgresql
matrix:
  include:
    - python: 3.7
      env: DJANGO="Django==2.2.16"
    - python: 3.7
      env: DJANGO="Django==3.0.10"
    - python: 3.8
      env: DJANGO="Django==3.0.10"
    - python: 3.8
      env: DJANGO="Django==3.1.1"
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements_test.txt
  - python -m playwright install
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python -Wd example_project/manage.py test django_mptt_example
  - cd frontend && yarn && yarn run build && cd ..
  - mkdir js_coverage
  - COVERAGE=true coverage run example_project/manage.py test django_mptt_example
  - cd coveralls
  - yarn && gem install coveralls-lcov
  - yarn run merge_coverage
  - coveralls-lcov -v -n coverage/lcov.info > coverage.json
  - cd ..
  - coverage report
after_success:
  - coveralls --merge=coveralls/coverage.json
