language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
install:
  - pip install Django==$DJANGO_VERSION
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install git+git://github.com/django-mptt/django-mptt.git; else pip install django-mptt==0.5.5; fi"
  - pip install -r example_project/requirements_test.txt
  - python setup.py install
script:
  - cd example_project
  - python manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,django_mptt_example manage.py test django_mptt_example
  - coverage report -m
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.5
